from pms.serializers.attendence import *
from pms.serializers.external_user import *
from pms.serializers.tender import *
from pms.serializers.project import *
from pms.serializers.machineries import *
from pms.serializers.manpower import *
from pms.serializers.pre_execution import *
from pms.serializers.requisition import *
from pms.serializers.approval_permission import *
from pms.serializers.tour_and_travel import *