from pms.views.external_user import *
from pms.views.tender import *
from pms.views.attendence import *
from pms.views.project import *
from pms.views.machineries import *
from pms.views.manpower import *
from pms.views.pre_execution import *
from pms.views.requisition import *
from pms.views.approval_permission import *
from pms.views.tour_and_travel import *